version: '3.8'
services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:4200

  spring:
    build:
      context: ../../Pharmacy_Management_Backend2
      dockerfile: Dockerfile
    ports:
      - 9090:8080
    environment:
      - SPRING_DATABASE_URL=jdbc:mysql://db:3307/test
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3307:3306

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
